package com.demo.springreactivedemo.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;

/**
 * Loads yaml properties generated by build gradle task - createProperties.
 * Yaml properties generation described in buildSrc/src/main/groovy/CreatePropertiesTask.groovy.
 */
@Configuration
@PropertySource(value = "classpath:version.yml", factory = YamlPropertySourceFactory.class, ignoreResourceNotFound = true)
public class PropertySourceConfiguration {}
